services:
  postgres:
    image: gui2310g/postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build: .
    image: api-projetonest
    container_name: nest-app
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PROFILES_ACTIVE: ${PROFILES_ACTIVE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/src
      - /src/node_modules
    networks:
      - my-network
    command: npm run start:dev 

  pgadmin:
    image: gui2310g/pgadmin
    container_name: my-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
